### ISSUE TITLE
Сайт кринж

### ISSUE THREAD

**Issue by Barn00** [Rezoc56/rezoc56.github.io#1]
Переделывай короче 🤙🔥🤯💦📉🎣👩‍💻🪦👩‍💻🚓🐓👎👎🦆👎🐷🇺🇲🇬🇧🇬🇧🇬🇧🔮🤯😱🔥🦈🎣🎣

**Comment by Rezoc56** [comment]
не
![IMG_20240319_020109_326](https://github.com/Rezoc56/rezoc56.github.io/assets/128143178/b21cf79a-417f-4287-a86d-436e3f04794b)
